version: "3.8"
services:
  database:
    image: rafalwolny/wsb-project-database:TAG
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password  # EDIT ME
      MYSQL_DATABASE: wsb            # EDIT ME
    volumes:
      - ./database/.data:/var/lib/mysql

  backend:
    image: rafalwolny/wsb-project-backend:TAG
    restart: on-failure
    environment:
      MYSQL_DATABASE: wsb       # EDIT ME
      MYSQL_USER: root          # EDIT ME
      MYSQL_PASSWORD: password  # EDIT ME
      MYSQL_HOST: database      # EDIT ME
    depends_on:
      - database

  api:
    image: rafalwolny/wsb-project-api:TAG
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:rw
    depends_on:
      - backend
