version: "3.8"
services:
  database:
    build: ./database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./database/.data:/var/lib/mysql

  backend:
    build: ./backend
    restart: on-failure
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    depends_on:
      - database

  api:
    build: ./api
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ./api/conf.d/default.conf:/etc/nginx/conf.d/default.conf:rw
    depends_on:
      - backend
